theme = "transparentjelly"

[editor]
true-color = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"backspace" = {b = ":sh mvn package -PskipTests=true &"}
